// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecruitmentManager.Models;

public partial class Application
{
    public int Id { get; set; }

    public int ApplicantId { get; set; }

    public int JobId { get; set; }

    public virtual Candidate Applicant { get; set; }

    public virtual Job Job { get; set; }
}