// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecruitmentManager.Models;

/// <summary>
/// Candidate information submitted with job application
/// </summary>
public partial class Candidate : Credentials
{
    public string Education { get; set; }

    public string Major { get; set; }

    public DateOnly? ExpectedGraduationDate { get; set; }

    public string Industries { get; set; }

    public byte[] Resume { get; set; }
}