// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace RecruitmentManager.Models;

/// <summary>
/// Candidate information submitted with job application
/// </summary>
public partial class Candidate 
{
    [Key]
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string? PreferredName { get; set; }

    [Phone]
    public string Phone {  get; set; }

    [EmailAddress]
    public string Email { get; set; }

    public string EducationDegree { get; set; }

    public string Major { get; set; }

    public string? OtherMajor { get; set; }

    public bool HasGraduated { get; set; }

    public DateOnly? ExpectedGraduationDate { get; set; }

    public string Industries { get; set; }

    public byte[] Resume { get; set; }

    public bool IsEmploymentEligible { get; set; }

    [Timestamp]
    public DateTime? DateSubmitted { get; } = DateTime.Now;

    public string? Comment { get; set; }

    /// <summary>
    /// Jobs applied for
    /// </summary>
    public List<string> Jobs { get; set; }
}