// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecruitmentManager.Models;

/// <summary>
/// Job postings; JSON array
/// </summary>
public partial class Job
{
    public int Id { get; set; }

    public string Position { get; set; }

    public decimal StartingSalary { get; set; }

    public string Location { get; set; }

    public DateOnly? EndDate { get; set; }

    public string MinimumQualifications { get; set; }

    public string SpecialRequirements { get; set; }

    public string PrimaryFunctions { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();
}