// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentManager.Data;

#nullable disable

namespace RecruitmentManager.Migrations
{
    [DbContext(typeof(HRMSContext))]
    [Migration("20250116222109_CandidateRefactor2")]
    partial class CandidateRefactor2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RecruitmentManager.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationDegree")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpectedGraduationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasGraduated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Industries")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmploymentEligible")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Jobs")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherMajor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Resume")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("RecruitmentManager.Models.Job", b =>
                {
                    b.Property<int>("PIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExternalClosingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExternalPostingStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FirstTimePosted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("InternalClosingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InternalPostingStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinimumQualifications")
                        .HasColumnType("TEXT");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryFunctions")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartingSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PIN");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
